import Footer from "../components/Footer";
import Header from "../components/Header";
import Script from "next/script";
import "../styles/index.css"
import Head from "next/head";

function MyApp({Component, pageProps}) {
    return (
        <div>
            <Head>
                <title>Новогодний портал Республики Тыва</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
                <link rel="icon" href="/tuvan_herb.png"/>
            </Head>
            <Header/>
            <Component {...pageProps} />
            <Footer/>

            <Script src="https://lidrekon.ru/slep/js/jquery.js" strategy="afterInteractive"></Script>
            <Script src="https://lidrekon.ru/slep/js/uhpv-full.min.js" strategy="afterInteractive"></Script>
        </div>
    )
}

export default MyApp
